import { leakedPromptsUpdatedChannel } from '@shared/events/appEvents';
import {
  LEAKED_PROMPTS_REPO,
  parseLeakedPromptFilename,
  type LeakedPromptList,
  type LeakedPromptMeta,
} from '@shared/leaked-prompts';
import { events } from '@main/lib/events';

type Snapshot = {
  sourceRepo: string;
  sourceCommit: string;
  entryCount: number;
  entries: (LeakedPromptMeta & { content: string })[];
};

const TREE_URL = `https://api.github.com/repos/${LEAKED_PROMPTS_REPO}/git/trees/main?recursive=1`;
const rawUrl = (filename: string) =>
  `https://raw.githubusercontent.com/${LEAKED_PROMPTS_REPO}/main/${filename}`;
const FETCH_TIMEOUT_MS = 10_000;

/**
 * Read-only gallery of github.com/jujumilk3/leaked-system-prompts. A bundled
 * snapshot (generated by scripts/generate-leaked-prompts-snapshot.ts) makes the
 * gallery work offline and render instantly; on first use we revalidate the
 * manifest against GitHub (stale-while-revalidate), so prompts added upstream
 * after the snapshot was cut still appear. Content for entries not present in
 * the snapshot is fetched lazily and memoised. Network failures are swallowed —
 * the snapshot is always a valid fallback.
 */
export class LeakedPromptsService {
  private snapshotPromise: Promise<Snapshot> | null = null;
  private snapshotContent = new Map<string, string>();
  private manifest = new Map<string, LeakedPromptMeta>();
  private contentOverlay = new Map<string, string>();
  private revalidatePromise: Promise<void> | null = null;
  private revalidated = false;
  private sourceCommit = 'unknown';

  private async ensureLoaded(): Promise<void> {
    if (!this.snapshotPromise) {
      // Imported as a raw string and parsed lazily: keeps the multi-MB snapshot
      // out of the startup bundle and out of tsc's literal-type inference.
      this.snapshotPromise = import('./leaked-prompts-snapshot.json?raw').then(
        (module) => JSON.parse(module.default) as Snapshot
      );
      const snapshot = await this.snapshotPromise;
      this.sourceCommit = snapshot.sourceCommit;
      for (const { content, ...meta } of snapshot.entries) {
        this.manifest.set(meta.id, meta);
        this.snapshotContent.set(meta.id, content);
      }
    }
    await this.snapshotPromise;
  }

  async list(): Promise<LeakedPromptList> {
    await this.ensureLoaded();
    // Fire-and-forget the first revalidation; the UI refreshes via the event.
    if (!this.revalidated) void this.revalidate();
    return this.buildList();
  }

  async refresh(): Promise<LeakedPromptList> {
    await this.ensureLoaded();
    await this.revalidate();
    return this.buildList();
  }

  async getContent(id: string): Promise<string | null> {
    await this.ensureLoaded();
    const overlay = this.contentOverlay.get(id);
    if (overlay !== undefined) return overlay;
    const bundled = this.snapshotContent.get(id);
    if (bundled !== undefined) return bundled;
    // Entry discovered via revalidation but not in the snapshot: fetch on demand.
    const meta = this.manifest.get(id);
    if (!meta) return null;
    const content = await this.fetchText(rawUrl(meta.filename));
    if (content === null) return null;
    this.contentOverlay.set(id, content);
    return content;
  }

  private buildList(): LeakedPromptList {
    const entries = [...this.manifest.values()].sort(
      (a, b) => b.date.localeCompare(a.date) || a.title.localeCompare(b.title)
    );
    return { sourceCommit: this.sourceCommit, revalidated: this.revalidated, entries };
  }

  private revalidate(): Promise<void> {
    if (!this.revalidatePromise) {
      this.revalidatePromise = this.doRevalidate().finally(() => {
        this.revalidatePromise = null;
      });
    }
    return this.revalidatePromise;
  }

  private async doRevalidate(): Promise<void> {
    const body = await this.fetchText(TREE_URL, {
      Accept: 'application/vnd.github+json',
    });
    if (body === null) return;
    let filenames: string[];
    try {
      const tree = JSON.parse(body) as { tree?: { path?: string; type?: string }[] };
      filenames = (tree.tree ?? [])
        .filter((node) => node.type === 'blob' && node.path && !node.path.includes('/'))
        .map((node) => node.path as string)
        .filter((path) => path.endsWith('.md') && path !== 'README.md');
    } catch {
      return;
    }
    if (filenames.length === 0) return;

    const next = new Map<string, LeakedPromptMeta>();
    for (const filename of filenames) {
      const meta = parseLeakedPromptFilename(filename);
      next.set(meta.id, meta);
    }
    const changed =
      next.size !== this.manifest.size || [...next.keys()].some((id) => !this.manifest.has(id));
    this.manifest = next;
    // Drop cached content for entries that no longer exist upstream.
    for (const id of this.contentOverlay.keys()) {
      if (!next.has(id)) this.contentOverlay.delete(id);
    }
    const wasRevalidated = this.revalidated;
    this.revalidated = true;
    if (changed || !wasRevalidated) events.emit(leakedPromptsUpdatedChannel, undefined);
  }

  private async fetchText(url: string, headers?: Record<string, string>): Promise<string | null> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const response = await fetch(url, {
        signal: controller.signal,
        headers: { 'User-Agent': 'yoda-app', ...headers },
      });
      if (!response.ok) return null;
      return await response.text();
    } catch {
      return null;
    } finally {
      clearTimeout(timer);
    }
  }
}

export const leakedPromptsService = new LeakedPromptsService();
