import type { RuntimeId } from '@shared/runtime-registry';
import type { TaskNamingContextSnapshot, TaskNamingStatus } from '@shared/task-naming';

export type Conversation = {
  id: string;
  projectId: string;
  taskId: string;
  runtimeId: RuntimeId;
  title: string;
  createdAt?: string;
  updatedAt?: string;
  archivedAt?: string | null;
  lastInteractedAt: string | null;
  resume?: boolean;
  autoApprove?: boolean;
  isInitialConversation: boolean | null;
};

export type ConversationSessionInfo = {
  sessionId: string;
  sessionTitle?: string;
  resumeCommand?: string;
  running?: boolean;
  tmuxEnabled?: boolean;
};

export type RenameConversationParams = {
  conversationId: string;
  newTitle: string;
};

export type ConversationNamingSnapshot = {
  conversationId: string;
  projectId: string;
  taskId: string;
  status: TaskNamingStatus;
  model: string | null;
  runtimeId: RuntimeId | null;
  runtimeName: string | null;
  context: TaskNamingContextSnapshot | null;
  systemPrompt?: string;
  systemPromptEstimatedTokens?: number;
  prompt?: string;
  promptChars?: number;
  promptEstimatedTokens?: number;
  generatedTitle?: string;
  error?: string;
  createdAt: string;
  updatedAt: string;
};

export type ClaudeTodoStatus = 'pending' | 'in_progress' | 'completed';

export type ClaudeTodo = {
  content: string;
  activeForm?: string;
  status: ClaudeTodoStatus;
};

export type ClaudeSessionMetadata = {
  summary: string | null;
  todos: ClaudeTodo[];
  model: string | null;
};

export type ClaudeSessionPrompt = {
  id: string;
  text: string;
  timestamp: string | null;
};

export type ClaudeMemoryFile = {
  kind: 'global-claude' | 'project-claude' | 'project-agents';
  path: string;
  content: string;
  bytes: number;
};

export type CodexMemoryFile = {
  kind: 'global-codex-agents' | 'project-agents' | 'project-codex-agents';
  path: string;
  content: string;
  bytes: number;
};

export type ClaudeMcpServer = {
  name: string;
  instructions: string;
};

export type ContextSkill = {
  name: string;
  description: string;
  path: string;
};

export type ClaudeSessionContext = {
  transcriptPath: string;
  memoryFiles: ClaudeMemoryFile[];
  tools: string[];
  agents: string[];
  mcpServers: ClaudeMcpServer[];
  skills: ContextSkill[];
  skillsListing: string | null;
  prompts: ClaudeSessionPrompt[];
  messages: SessionTranscriptMessage[];
  /** Latest compaction summary the runtime wrote into the transcript, if any. */
  summary: SessionSummary | null;
};

/**
 * A summary the agent runtime itself produced during context compaction
 * (Claude Code's `isCompactSummary` row / Codex's SUMMARY_PREFIX message).
 * Extracted from the transcript — never generated by us.
 */
export type SessionSummary = {
  text: string;
  timestamp: string | null;
};

export type SessionTranscriptMessage = {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  timestamp: string | null;
};

/**
 * Which slice of the session a summary covers.
 * - `global`: the whole session (prefers the runtime compaction summary)
 * - `recent`: only the last few transcript messages (short, refreshed each turn)
 */
export type SessionSummaryScope = 'global' | 'recent';

/**
 * Outcome of resolving a session summary. `status` explains the absence of a
 * summary so the UI can show a meaningful message instead of a blank state.
 * - `compaction`: surfaced the runtime's own compaction summary
 * - `generated`: summarized the conversation on demand
 * - `running`: session is mid-turn; will summarize once idle
 * - `empty`: no user prompts to summarize yet
 * - `failed`: generation was attempted but produced nothing
 * - `unsupported`: provider has no summary support
 */
export type SessionSummaryStatus =
  | 'compaction'
  | 'generated'
  | 'running'
  | 'empty'
  | 'failed'
  | 'unsupported';

export type SessionSummaryResult = {
  summary: SessionSummary | null;
  status: SessionSummaryStatus;
};

export type CodexDynamicTool = {
  name: string;
  namespace: string | null;
  description: string;
  inputSchema: string;
  deferLoading: boolean;
};

export type CodexTurnContext = {
  turnId: string | null;
  model: string | null;
  approvalPolicy: string | null;
  sandboxPolicy: string | null;
  effort: string | null;
};

export type CodexSessionContext = {
  threadId: string;
  rolloutPath: string | null;
  title: string;
  cwd: string;
  model: string | null;
  modelProvider: string | null;
  cliVersion: string | null;
  memoryMode: string | null;
  approvalMode: string | null;
  sandboxPolicy: string | null;
  baseInstructions: string | null;
  developerMessages: ClaudeSessionPrompt[];
  memoryFiles: CodexMemoryFile[];
  dynamicTools: CodexDynamicTool[];
  skills: ContextSkill[];
  skillsListing: string | null;
  prompts: ClaudeSessionPrompt[];
  messages: SessionTranscriptMessage[];
  turnContexts: CodexTurnContext[];
  completedTurnCount: number;
  /** Latest compaction summary the runtime wrote into the rollout, if any. */
  summary: SessionSummary | null;
};

export type CreateConversationParams = {
  id: string;
  projectId: string;
  taskId: string;
  runtime: RuntimeId;
  title: string;
  autoApprove?: boolean;
  isInitialConversation?: boolean;
  initialSize?: { cols: number; rows: number };
  initialPrompt?: string;
  /** Absolute local paths of image attachments to deliver with the initial prompt. */
  imagePaths?: string[];
};
