import type {
  SessionSummary,
  SessionSummaryScope,
  SessionSummarySnapshot,
  SessionSummaryStatus,
} from '@shared/conversations';
import { defineEvent } from '@shared/ipc/events';

/**
 * Streaming session-summary updates (SSE-style). Emitted from the main process
 * while a summary is being generated by the provider CLI, keyed by a topic of
 * `${conversationId}:${scope}` so each blind only sees its own stream.
 *
 * - `delta` arrives repeatedly as the CLI streams stdout; the renderer appends.
 * - the terminal event carries `done: true` with the final `summary`/`status`.
 */
export type SessionSummaryStreamEvent = {
  scope: SessionSummaryScope;
  /** Incremental text appended to the in-progress summary. */
  delta?: string;
  /** Set on the terminal event. */
  done?: boolean;
  /** Final summary on the terminal event (null if generation produced nothing). */
  summary?: SessionSummary | null;
  /** Final status on the terminal event. */
  status?: SessionSummaryStatus;
};

export const sessionSummaryStreamChannel =
  defineEvent<SessionSummaryStreamEvent>('session-summary:stream');

/** Topic for a given conversation + scope stream. */
export function sessionSummaryTopic(conversationId: string, scope: SessionSummaryScope): string {
  return `${conversationId}:${scope}`;
}

/**
 * Emitted whenever the whole-session summary debug snapshot changes (idle →
 * generating → ready/failed), mirroring `conversationNamingUpdatedChannel`.
 */
export const sessionSummarySnapshotUpdatedChannel = defineEvent<SessionSummarySnapshot>(
  'session-summary:snapshot-updated'
);
